name: 'olympic_env'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - docopt=0.6.*
  - pandas=1.3.*
  - altair=4.1.*
  - altair_viewer=0.4.*
  - altair_saver=0.5.*
  - pandoc=2.16.*